# tasks file for top
---
- name: install
  apt:
    name: procps
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags: [configuration, top, top-install]

- name: create configuration file
  copy:
    src: etc/skel/.toprc
    dest: "{{ item.value.dest }}/.toprc"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default(item.value.owner) | default('root') }}"
    mode: "{{ item.value.mode | default('0644') }}"
    force: "{{ 'yes' if top_replace_toprc else 'no' }}"
  with_dict: top_toprc_destinations
  tags: [configuration, top, top-configuration]
