---
# tasks file for top
- name: install
  apt:
    name: procps
    state: latest
  tags: [configuration, top, top-install]

- name: create configuration file
  copy:
    src: etc/skel/.toprc
    dest: "{{ item }}/.toprc"
    owner: root
    group: root
    mode: 0644
    force: "{{ 'yes' if top_replace_toprc else 'no' }}"
  with_items: top_toprc_destinations
  tags: [configuration, top, top-configuration]
